projects:
  communicationsmanager:
    schemaPath: amplify/backend/api/communicationsmanager/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ca-central-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
