export const languageData = {
  en: {
    // pre-signin/pre-signup
    welcome: "Welcome!",
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    createAccount: "Create An Account",
    // profile creation
    setUpProfile: "Set Up Profile",
    missingRequiredField: "Please fill in the required fields.",
    generalInfo: "General Information",
    profilePrompt: "Please start by providing general information",
    province: "Province",
    postalCode: "Postal Code",
    notifPreferencePrompt: "Select your notification preferences:",
    missingNoticePreference: "Please select your notification preferences.",
    invalidPhone: "Please enter a valid phone number.",
    invalidEmail: "Please enter a valid email.",
    invalidPostalCode: "Please enter a valid postal code.",
    accountsExists: "An account with the given email already exists.",
    emailNotice: "Email Notifications",
    textNotice: "Text Notifications",
    profileCreated: "Your user profile has been created",
    phoneNoFound: "No Phone Number Found",
    missingPhoneNo: `You have not yet provided a phone number for notifications.
              Enter your phone number below to continue.`,
    emptyFieldErr: "This field cannot be empty.",
    // verification
    verification: "Verification",
    verifyAccount: "Verify Account",
    verify: "Verify",
    verificationSent: "A verification code has been sent to ",
    checkEmailVerification:
      "Please check your email for a confirmation code. This may take several minutes.",
    forgotpassword: "Forgot your password?",
    invalidVerificationCode:
      "Invalid verification code provided, please try again.",
    newVerifyCodeSent: "New verification code sent successfully.",
    verifyCodePrompt: "Enter your verification code.",
    noReceiveVerifyCode: "Didn't receive your verification code?",
    resendCode: "Resend Code",
    maxIncorrectAttempts: "Too many incorrect attempts.",
    UserNone: "User does not exist.",
    confirmationPrompt: "Enter your confirmation code",
    // select categories
    selectCategories: "Categories of Interest",
    selectCategoriesTitle: "Select Categories of Interest",
    initialCategoriesSelect:
      "Select categories of interest that you would like to receive notifications from. Your notification preferences can be changed at any time.",
    currentSelection: "Currently Selected:",
    // admin edit category
    createCategory: "Create A New Category",
    selectTopic: "Select an existing topic",
    addTopic: "Add New Topic ...",
    editCategory: "Edit Category",
    titleEn: "English Title *",
    titleFr: "French Title",
    acronym: "Acronym *",
    descriptionEn: "Description in English",
    descriptionFr: "Description in French",
    uploadImg: "Upload Image",
    search: "Search...",
    add: "Add ...",
    delete: "Delete",
    confirmProceed: "Are you sure you wish to proceed?",
    confirmDeleteCategory:
      "Doing so will remove the selected categories for all users.",
    confirmDeleteTopic:
      "Doing so will remove the selected topics for all categories.",
    nocurrentCategories: "Currently no categories",
    nocurrentTopics: "Currently no topics",
    missingValue: "No value entered.",
    topicExistsErr: "Topic already exists.",
    // user profile edit
    emailUpdateSuccess: "Your email has been successfully updated.",
    confirmLeavePage: "Leaving Page?",
    changesNotSaved:
      "Your changes have not been saved. Do you want to leave without saving?",
    phoneNoSaved: "Your phone number has been successfully saved.",
    accountExistsErr: "An account with the given email already exists.",
    subscribeTab: "Subscribe to Topics",
    editAccountTab: "Edit Account Information",
    subscribedFilter: "Subscribed only",
    // nav
    logout: "Logout ",
    // steps
    back: "Back",
    next: "Next",
    save: "Save",
    cancel: "Cancel",
    success: "Success!",
    done: "Done",
    yes: "Yes",
    no: "No",
    continue: "Continue",
    thankyou: "Thank You!",
    // provinces
    ab: "Alberta",
    bc: "British Columbia",
    mb: "Manitoba",
    nb: "New Brunswick",
    nl: "Newfoundland and Labrador",
    nt: "Northwest Territories",
    ns: "Nova Scotia",
    nu: "Nunavut",
    on: "Ontario",
    pe: "Prince Edward Island",
    qc: "Quebec",
    sk: "Saskatchewan",
    yt: "Yukon",
  },
  fr: {
    // pre-signin/pre-signup
    welcome: "Bienvenue",
    signIn: "S'identifier",
    signUp: "S'inscrire",
    email: "E-mail",
    createAccount: "Créer un compte",
    // profile creation
    setUpProfile: "Configurer le profil utilisateur",
    missingRequiredField: "S'il vous plaît remplir les champs obligatoires.",
    generalInfo: "Informations générales",
    profilePrompt: "Veuillez commencer par fournir des informations générales",
    province: "Province",
    postalCode: "code postal",
    notifPreferencePrompt: "Sélectionnez vos préférences de notification :",
    missingNoticePreference:
      "Veuillez sélectionner vos préférences de notification.",
    invalidPhone: "S'il vous plaît entrer un numéro de téléphone valide.",
    invalidEmail: "Veuillez saisir une adresse e-mail valide.",
    invalidPostalCode: "Veuillez entrer un code postal valide.",
    accountsExists: "Un compte avec l'adresse e-mail indiquée existe déjà.",
    emailNotice: "Notifications par email",
    textNotice: "Notifications textuelles",
    profileCreated: "Votre profil utilisateur a été créé",
    phoneNoFound: "Aucun numéro de téléphone trouvé",
    missingPhoneNo: `Vous n'avez pas encore fourni de numéro de téléphone pour les notifications.
               Entrez votre numéro de téléphone ci-dessous pour continuer.`,
    emptyFieldErr: "Ce champ ne peut pas être vide.",
    // verification
    verification: "Vérification",
    verifyAccount: "vérifier le compte",
    verify: "Vérifier",
    verificationSent: "Un code de vérification a été envoyé à ",
    checkEmailVerification:
      "Veuillez vérifier votre e-mail pour un code de confirmation. Cela peut prendre plusieurs minutes.",
    forgotpassword: "Mot de passe oublié?",
    invalidVerificationCode:
      "Code de vérification fourni non valide, veuillez réessayer.",
    newVerifyCodeSent: "Nouveau code de vérification envoyé avec succès.",
    verifyCodePrompt: "Entrez votre code de vérification.",
    noReceiveVerifyCode: "Vous n'avez pas reçu votre code de vérification ?",
    resendCode: "Renvoyer le code",
    maxIncorrectAttempts: "Trop de tentatives incorrectes.",
    UserNone: "L'utilisateur n'existe pas.",
    confirmationPrompt: "Entrez votre code de confirmation",
    // select categories
    selectCategories: "Catégories d'intérêt",
    selectCategoriesTitle: "Sélectionnez les catégories d'intérêt",
    initialCategoriesSelect:
      "Sélectionnez les catégories d'intérêt pour lesquelles vous souhaitez recevoir des notifications. Vos préférences de notification peuvent être modifiées à tout moment.",
    currentSelection: "Actuellement sélectionné :",
    // admin edit category
    createCategory: "Créer une nouvelle catégorie",
    selectTopic: "Sélectionnez un sujet existant",
    addTopic: "Ajouter un nouveau sujet",
    editCategory: "Modifier la catégorie",
    titleEn: "Titre anglais *",
    titleFr: "Titre français",
    acronym: "Acronyme *",
    descriptionEn: "Descriptif en anglais",
    descriptionFr: "Descriptif en français",
    uploadImg: "Télécharger l'image",
    search: "Chercher",
    add: "Ajouter ...",
    delete: "Effacer",
    confirmProceed: "Êtes-vous sûr de vouloir continuer?",
    confirmDeleteCategory:
      "Cela supprimera les catégories sélectionnées pour tous les utilisateurs.",
    confirmDeleteTopic:
      "Cela supprimera les sujets sélectionnés pour toutes les catégories.",
    nocurrentCategories: "Actuellement aucune catégorie",
    nocurrentTopics: "Aucun sujet pour le moment",
    missingValue: "Aucune valeur saisie.",
    topicExistsErr: "Le sujet existe déjà.",
    // user profile edit
    emailUpdateSuccess: "Your email has been successfully updated.",
    confirmLeavePage: "Leaving Page?",
    changesNotSaved:
      "Vos modifications n'ont pas été enregistrées. Voulez-vous quitter sans enregistrer ?",
    phoneNoSaved: "Votre numéro de téléphone a été enregistré avec succès.",
    accountExistsErr: "Un compte avec l'adresse e-mail indiquée existe déjà.",
    subscribeTab: "Abonnez-vous aux sujets",
    editAccountTab: "Modifier les informations du compte",
    subscribedFilter: "Abonné uniquement",
    // nav
    logout: "Se déconnecter ",
    // steps
    back: "Arrière",
    next: "Suivante",
    save: "Sauver",
    cancel: "Annuler",
    success: "Succès!",
    done: "Fait",
    yes: "Oui",
    no: "Non",
    continue: "Continuer",
    thankyou: "Merci!",
    // provinces
    ab: "Alberta",
    bc: "Colombie britannique",
    mb: "Manitoba",
    nb: "Nouveau-Brunswick",
    nl: "Terre-Neuve-et-Labrador",
    nt: "Territoires du nord-ouest",
    ns: "Nouvelle-Écosse",
    nu: "Nunavut",
    on: "Ontario",
    pe: "Île-du-Prince-Édouard",
    qc: "Québec",
    sk: "Saskatchewan",
    yt: "Yukon",
  },
};
